#!/bin/bash

#author : fatih

set -e

RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

mice_file=/var/run/mice.pid
log_file=/var/log/eta.log
count_file=/usr/share/count

now=$(date +"%T")

vmid="$ID_VENDOR_ID:$ID_MODEL_ID"

if [ ! -f $count_file ];then
	echo "0" > $count_file
fi

if [ $1 == "udev" ]; then
	if [ $2 == "plugged" ]; then
		phase1="0"
		phase2="0"
		if echo "$vmid" | grep -qE "(2621:2201|2621:4501)" ; then
			phase2="1"
		elif echo "$vmid" | grep -qE "(6615:0084|6615:0085|6615:0086|6615:0087|6615:0088|6615:0c20)" ; then
			phase1="1"
		fi
		if ([ $phase1 == "0" ] && [ $phase2 == "0" ]); then
			count=$(lsusb | grep -i mouse | wc -l)
			echo "$count" > $count_file
			count=`cat $count_file`
			if [ $count == 1 ]; then
				echo `touch $mice_file`
				echo -e "${RED}$0${NC} : mouse is plugged - $now" >> $log_file
			else
				echo -e "${RED}$0${NC} : a mouse is already plugged - $now" >> $log_file
				if [ ! -f $mice_file ];then
					echo `touch $mice_file`
				fi
			fi
		fi
	elif [ $2 == "unplugged" ]; then
		phase1="0"
		phase2="0"
		if echo "$vmid" | grep -qE "(2621:2201|2621:4501)" ; then
			phase2="1"
		elif echo "$vmid" | grep -qE "(6615:0084|6615:0085|6615:0086|6615:0087|6615:0088|6615:0c20)" ; then
			phase1="1"
		fi
		if ([ $phase1 == "0" ] && [ $phase2 == "0" ]); then
			count=$(lsusb | grep -i mouse | wc -l)
			echo "$count" > $count_file
			count=`cat $count_file`
			if [ $count -gt 0 ]; then
				echo -e "${RED}$0${NC} : a mouse is unplugged but another mouse is already plugged - $now" >> $log_file
				if [ ! -f $mice_file ];then
					echo `touch $mice_file`
				fi
			else
				echo `rm $mice_file`
				echo -e "${RED}$0${NC} : mouse is unplugged - $now" >> $log_file
			fi
		fi
	fi
elif [ $1 == "systemd" ]; then
	count=$(lsusb | grep -i mouse | wc -l)
	echo "$count" > $count_file
	count=`cat $count_file`
	if [ $count == 0 ]; then
		echo `rm $mice_file`
		echo -e "${RED}$0${NC} : no mouse detected on start - $now" >> $log_file
	fi
fi
